CREATE TYPE meal_times AS ENUM (
    'breakfast',
    'lunch',
    'dinner',
);
CREATE TABLE IF NOT EXISTS meals (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    calories INTEGER  DEFAULT 0
);

CREATE TABLE IF NOT EXISTS mealTimes (
    
)